### ISSUE TITLE
About the reflectivity of hard targets

### ISSUE THREAD

**Issue by Lagrange0** [MartinHahner/LiDAR_fog_sim#17]
Thank you for your excellent work. I have a question about the reflectivity of hard targets.

Lines 156-157 of fog_simulation.py:

```
# reflectivity of the hard target [0.07, 0.2, > 4 => low, normal, high]
self.gamma = 0.000001
```

The comment on line 156 mentions that the reflectivity gamma of a normal object is approximately 0.2. Why is gamma set to 1e-6 in the code? 
Section 4.2 of the paper mentions that setting the reflectivity in this way better aligns with the point cloud intensity distribution of the STF dataset. How is this measured? What specific metrics are used?

**Comment by MartinHahner** [comment]
Hi and thanks for your interest in our work. <br>
We did not quanitavely measure it with any metric (because we did not know any metric which captures the similarity of point clouds), maybe there is a metric now, but at the time, we only visually / qualitatively compared the point clouds in terms of there intensity. 

In other words, we color coded the points according to their intensity and then adjusted gamma to match what we saw in the real data.
