### ISSUE TITLE
Problem about loading openpcdet result.pkl

### ISSUE THREAD

**Issue by zitgit** [MartinHahner/LiDAR_fog_sim#5]
Hi! I came from OpenPCDet issues channel and found your amazing work! 
But I have a problem about loading the result.pkl with kitti velodyne data. I can't visualize the predicted bbox in the point cloud.
Is there anything wrong with my file path with the pickle?
Thanks a lot in advance! The interface is really great.
![image](https://user-images.githubusercontent.com/42319139/150265966-a5c0d3be-d4b8-406e-a888-9885c37131de.png)

**Comment by MartinHahner** [comment]
Hi @zitgit,

in my code I check for `suffix == ".pickle"`, 
so maybe you just need to change the filename from `result.pkl` to `result.pickle`.

Otherwise, it is best if you debug through the code yourself and see if the methods mentioned below are called at all. 

https://github.com/MartinHahner/LiDAR_fog_sim/blob/641ca97faef3d9f446c0a6d61f2f447a4b4e39e2/pointcloud_viewer.py#L1282

https://github.com/MartinHahner/LiDAR_fog_sim/blob/641ca97faef3d9f446c0a6d61f2f447a4b4e39e2/pointcloud_viewer.py#L1349

Please let me know if changing the filename helped or if you have further questions.

**Comment by zitgit** [comment]
Thanks for your reply! @MartinHahner 
Changing the filename didn't work for me. But I will debug through the code! Thanks again!
